app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication routes...
Route::get('/', 'Auth\AuthController@getLogin');
Route::get('admin/login', 'Auth\AuthController@getLogin');
Route::post('admin/login', 'Auth\AuthController@postLogin');
Route::get('admin/logout', 'Auth\AuthController@getLogout');


// secure admin pages in group.
Route::group(['middleware' => 'auth'],
    function()
    {
        Route::get('admin/dash', 'DashController@index');
        Route::resource('admin/courses', 'CoursesController');
        Route::resource('admin/modules', 'ModulesController');
        Route::resource('admin/items', 'ItemsController');
        Route::resource('admin/itemmodule', 'ItemModuleController');


    }
);

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;
class Module extends Model
{
    protected $table = 'modules';
    protected $fillable = ['title', 'code', 'leader'];

    public function courses()
    {
        return $this->belongsToMany('App\Course')->withTimestamps();
    }

    public function items()
    {
        return $this->belongsToMany('App\Item')->withPivot('complete')->withTimestamps()->orderBy('text', 'asc');
    }

    public static function itemModuleAssociations($id)
    {
        // set global variables
        $GLOBALS['module_id'] = $id;
        // create a join on multiple columns that also creates a new column 'checked'. This join can not be done in
        // eloquent as we need it to return all items, not just those which are associated as per the above items method.

        // first line returns all items
        // Second part left joins to the item_module table only for the specific module
        // this selects then gets all of the item data and adds an additional column' checked' making the value 1 if the association exists and 0 if it does not.
        // order the items by default and then by alpha.
        // the 'get' then simply runs the query.
        return DB::table('items')
            ->leftJoin('item_module', function($join)
            {
                $join->on('item_module.item_id', '=', 'items.id')
                    ->on('item_module.module_id', '=', DB::Raw($GLOBALS['module_id']));
            })
            ->select('items.*', DB::Raw('IF(`item_module`.`module_id` IS NULL, 0, 1) AS `checked`'))
            ->orderBy('items.default', 'desc')
            ->orderBy('text', 'asc')
            ->get();
    }
}

app/Http/Controllers/ModulesController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Module;
use App\ItemModule;
use App\Item;
use Illuminate\Http\Request;
use Redirect;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;
use DB;


class ModulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // return a list of all modules if module leader
        if(Auth::user()->admin == '2') {
            //get the module with the items join where the user id is current to the logged in user's id.
            $allModules = Module::with('items')->where('leader', Auth::user()->id)->get();
        } else {
            //Else just return all items for all modules (admin)
            $allModules = Module::with('items')->get();

        }
        //retrieve all modules count and assign to total
        $total = $allModules->count();
        //Return all completed items (1)
        $completed = ItemModule::where('complete', '=', '1')->get();

        //Old method
//        return view('admin.modules.list', ['allModules' => $allModules, 'complete' => $completed, 'total' => '$total']);

        //New method - Use php's array compact to pass multiple variables to the view
        return view('admin.modules.list', compact('allModules', 'total', 'completed'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        // Return all module leaders
        $users = User::where('admin', '2')->get();

        $itemModuleAssociations = Module::itemModuleAssociations(0);

        return view('admin.modules.create', ['users' => $users])->with(['itemModuleAssociations' => $itemModuleAssociations]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Requests\CreateModulesRequest $request)
    {
        $module = new Module;

        $module->title = $request->title;
        $module->code = $request->code;
        $module->leader = $request->moduleleader;

        $module->save();

        $itemModules = $request->get('itemModules');

        // write module associations
        if (count($itemModules) > 0 ) {
            foreach ($itemModules as $item_id) {
                DB::table('item_module')->insert([
                    'module_id' => $module->id, 'item_id' => $item_id
                ]);
            }
        }

        return Redirect::route('admin.modules.show', [$module]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        // return a single module based on module id
        $module = Module::findORFail($id);
        $moduleleader = User::find($module->leader);
        $allModules = Module::with('items')->where('leader', Auth::user()->id)->get();
        $total = $allModules->count();
        //Return all completed items (1)
        $completed = ItemModule::where('complete', '=', '1')->get();
        //Get all items marked as default
        $default = Item::where('default', '=', '1')->get();

        //Pass variables to the view.
        return view('admin.modules.show', ['module' => $module])->with(['moduleleader' => $moduleleader, 'total' => $total, 'completed' => $completed, 'allModules' => $allModules, 'default' => $default]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //Populate select box only with module leaders (admin status = 2)
        $users = User::where('admin', 2)
            ->orderBy('name', 'desc')
            ->get();
        $userselector = array();
        foreach($users as $user) {
            $userselector[$user->id] = $user->name;
        };
        $module = Module::findOrFail($id);
        // pass over two arrays/variables to the view.

        $itemModuleAssociations = Module::itemModuleAssociations($id);

        return view('admin.modules.edit', ['module' => $module])->with(['userselector' => $userselector])->with(['itemModuleAssociations' => $itemModuleAssociations]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Requests\CreateModulesRequest $request, $id)
    {
        $module = Module::findORFail($id);

        $module->update([

            'title' => $request->get('title'),
            'code' => $request->get('code'),
            'leader' => $request->get('moduleleader')
        ]);


        $itemModuleAssociations = Module::itemModuleAssociations($id);
        $itemModules = $request->get('itemModules');

        foreach ($itemModuleAssociations as $item)
        {
            $skipped = false;
            // error capture for having no items associated
            if (count($itemModules) > 0 ) {
                // check if association already exists if it does remove it from the $courseModules array then remove it frm the db
                if ($item->checked == 1 && (($key = array_search($item->id, $itemModules)) !== false)) {
                    unset($itemModules[$key]);
                    $skipped = true;
                }
            }
            // delete any removed associations
            if($item->checked == 1 && !$skipped)
            {
                DB::table('item_module')->where('module_id', '=', $id)->where('item_id', '=', $item->id)->delete();
            }
            unset($key);
        }
        // write module associations
        if (count($itemModules) > 0 ) {
            foreach ($itemModules as $item_id) {
                DB::table('item_module')->insert([
                    'module_id' => $id, 'item_id' => $item_id
                ]);
            }
        }

        return Redirect::route('admin.modules.show', $module->id)->with('message', 'Your module has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        // delete
        Module::destroy($id);

        // redirect
        //Session::flash('message', 'Successfully deleted the Module!');
        return \Redirect::route('admin.modules.index');
    }



}

resources/views/admin/modules/create.blade.php
@extends('layouts.master')

@section('title', 'Add a New Module')
@stop

@section('content')

    <h1 class="small-12 columns">Add new Module</h1>

    @if (count($errors) > 0)
        <div class="alert-box alert small-12 columns">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="POST" action="{{url('admin/modules') }}" enctype="multipart/form-data" id="form" data-abide>
        <!-- Title Form Input-->
        <div class="small-12 columns">
            <label for="Title">Title:</label>
            <input type="text" id="title" name="title" placeholder="Module Title" value="{{ Input::old('title') }}" required >
            <small class="error">A title is required.</small>
        </div>
        <!-- code Form Input-->
        <div class="small-12 columns">
            <label for="code">Module Code:</label>
            <input type="text" id="code" name="code" placeholder="Module Code" value="{{ Input::old('code') }}" required>
            <small class="error">A module code is required. example CIS1234</small>
        </div>
        <!-- Leader Form Dropdown-->
        <div class="small-12 columns">
            <label for="moduleleader">Leader:</label>
            <select id="moduleleader" name="moduleleader">
                @foreach($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
            </select>
        </div>
        <!-- add item association checkboxes partial blade -->
        <div class="row large-12 columns ">
            @if ( count($itemModuleAssociations) > 0)
                @include('admin.modules.itemModuleAssociations')
            @endif
        </div>
        <!-- Course submit button -->
        <div class="small-12 columns">
            <button id="submit" name="submit" class="button right">Create Module</button>
        </div>
        {!! csrf_field() !!}
    </form>

@stop

resources/views/admin/modules/edit.blade.php
@extends('layouts.master')

@section('title')
    Edit - {{ $module->title }}
@stop

@section('content')

    <h1 class="small-12 columns">Edit - {{ $module->title }}</h1>

    @if (count($errors) > 0)
        <div class="alert-box alert small-12 columns">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::model($module, array('method' => 'put', 'route' => ['admin.modules.update', $module->id], 'data-abide' => '')) !!}
        <!-- Title Form Input-->
        <div class="small-12 columns">
            {!! Form::label('title:', 'Module title:') !!}
            {!! Form::text('title', Input::old('title'), array('placeholder'=>'Module Title', 'required' => '')) !!}
        </div>

        <!-- code Form Input-->
        <div class="small-12 columns">
            {!! Form::label('code', 'Module code:') !!}
            {!! Form::text('code', Input::old('code'), array('placeholder'=>'Module Code', 'required' => '')) !!}
        </div>
        <!-- Leader Form Dropdown-->
        <div class="small-12 columns">
            {!! Form::label('moduleleader', 'Leader:') !!}
            <!-- moved the logic to the controller -->
            {!! Form::select('moduleleader', $userselector, $module->leader) !!}
        </div>
        <!-- add item association checkboxes partial blade -->
        <div class="row large-12 columns ">
            @if ( count($itemModuleAssociations) > 0)
                @include('admin.modules.itemModuleAssociations')
            @endif
        </div>
        <!-- Course submit button -->
        <div class="small-12 columns">
            {!! Form::submit('Update Module', array('class'=>'button right')) !!}
        </div>
        {!! csrf_field() !!}
    {!! Form::close() !!}
@stop

resources/views/admin/modules/itemModuleAssociations.blade.php
<?php
    $defaultCount = 0;
    $optionalCount = 0;
?>

@foreach($itemModuleAssociations as $item)
    @if ($item->default == 0)
         <?php  $optionalCount ++ ?>
    @endif
    @if ($item->default == 1)
        <?php $defaultCount ++ ?>
    @endif
    @if ($defaultCount == 1)
        <h2>Default Items</h2>

    @endif
    @if ($optionalCount == 1)
        <hr />
        <h2>Optional Items</h2>

    @endif

    <div class="small-12 columns">
        @if ($item->default == 0)
            {!! Form::checkbox('itemModules['.$item->id.']', $item->id, $item->checked ) !!}
        @else
            {!! Form::hidden('itemModules['.$item->id.']', $item->id) !!}
        @endif
            {!! Form::label('itemModules['.$item->id.']', $item->text) !!}
    </div>
@endforeach

resources/views/admin/modules/list.blade.php
@extends('layouts.master')
@section('title')
    All Modules
@stop
@section('content')
    <?php $adminstatus = (Auth::user()->admin) ?>
    @if ($adminstatus == '1')
        <h1>Modules <a href="{{ url('admin/modules/create') }}" class="button right success small">
                Add a new module
            </a></h1>
    @else
        <h1>Modules</h1>
        @endif

        @if(Auth::check())
                <!--  The user is logged in... -->
        <div class="row small-12 columns">

            @if ($adminstatus == '1')
                    <!-- return a list of all courses -->
            <div class="small-12 columns">
                @foreach($allModules as $aModule)
                    <div class="row">
                        {!! Form::open(array('url' => '/admin/modules/' . $aModule->id)) !!}
                        <a href="{{ route('admin.modules.show', [$aModule->id]) }}" class="item">{{ $aModule->title }}</a>
                        {!! Form::hidden('_method', 'DELETE') !!}
                        {!! Form::submit('Delete this Module', array('class' => 'button tiny alert right', 'id' => $aModule->title . ' delete', 'name' => $aModule->title . ' delete')) !!}
                        {!! Form::close() !!}
                        <hr />
                    </div>
                @endforeach

            </div>
            @elseif($adminstatus == '2')

                    <!-- return only courses the staff are course leaders of and if none then return a message saying none to show. -->
            <?php $myModules = $allModules; ?>

            <table class="large-12 columns">
                <thead>
                <tr>
                    <th>Available Modules</th>
                    <th>Module progress</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach ($myModules as $myModule)
                    <tr>
                        <td>
                            <a href="{{ route('admin.modules.show', [$myModule->id]) }}" class="item">{{ $myModule->title }}</a>
                        </td>
                        <td>
                            <!--return completed items associated with the module id-->
                            <?php $count = $completed->where('module_id', $myModule->id)->count(); ?>
                                    <!--Echo out the completed items associated with module-->
                            <!--Populate foundation progress bar with calculated percentage from helper function, based on amount of completed items-->
                            <div class="progress">
                                <span class="meter" style="width: {{ Math::percentage($count, $myModule->items->count(), TRUE)  }};">
                                    <!--Percentage text within the span element-->
                                    <p class="percent">{{Math::percentage($count, $myModule->items->count(), TRUE)}}</p>
                                </span>
                            </div>
                            <p>{{ $count }} out of {{ $myModule->items->count()  }} items completed.</p>
                        </td>

                        <td>
                            <!--Link to individual module progress page-->
                            <a href="{{ route('admin.modules.show', [$myModule->id]) }}" class="button tiny right">View module progress</a>

                        </td>

                    </tr>
                @endforeach
                </tbody>
            </table>


            @endif
        </div>

    @endif



@stop

resources/views/admin/modules/show.blade.php
@extends('layouts.master')
@section('title')
    Module - {{ $module->code }} - {{ $module->title }}
@stop
@section('content')

    @if ( Session::get('message'))
        <div class="alert-box warning large-12 columns">
            {{ Session::get('message') }}
            <a href="#" class="close">&times;</a>
        </div>
    @endif

    <h1 class="small-12 columns">{{ $module->title }}</h1>
    <div class="small-12 columns">
        <p> <strong>Module code:</strong> {{ $module->code }}</p>
        <p> <strong>Module Leader:</strong> {{ $moduleleader->name }}</p>

        <!--Module progress information if module leader-->
        @if(Auth::user()->admin =='2')
            <div class="panel text-center">
                <h2>{{$module->title}} Progress</h2>
                <p>Welcome to the {{$module->title}} progress page. Please feel free to observe module statistics and to add/remove items.</p>
                <div class="row">
                    <div class="large-4 columns">
                        <h3 class="subheader">Overall Completion</h3>
                        <!--retrieve completed item count associated with a module-->
                        <?php $total = $module->items->count();
                        $count = $completed->where('module_id', $module->id)->count()
                        ?>
                                <!--Insert completion percentage calculation-->
                        <p class="progress-text">{{Math::percentage($count, $total,  TRUE)}}</p>
                    </div>

                    <div class="large-4 columns">
                        <h3 class="subheader">Completed Items</h3>
                        <p class="progress-text">{{$count}}/{{$total}}</p>
                    </div>

                    <div class="large-4 columns">
                        <h3 class="subheader">Default Items</h3>
                        <p class="progress-text">{{$default->count()}}</p>
                    </div>
                </div>
            </div>
        @endif

        <h2>Associated Items</h2>
        @if (Auth::user()->admin == '2' )
            <a href="{{ route('admin.items.create', $module->id) }}" class="button small left success">Add Item</a>
        @endif
        @if ( !$module->items->count() )
            Your Module has no Items linked.
        @else
            <table class="large-12 columns">
                <thead>
                <tr>
                    <th>Item Description</th>
                    <th>Default</th>
                    @if(Auth::user()->admin =='2')
                        <th>Mark Complete/Incomplete</th>
                        <th>Delete Item</th>
                    @endif
                </tr>
                </thead>

                <tbody>
                @foreach( $module->items as $item )
                    <tr>
                        <td>
                            <p class="small-8 columns">{{ $item->text }}</p>
                            <!-- <form method="PUT" action="{{url('/admin/itemmodule') }}" enctype="multipart/form-data" id="form" data-abide> -->
                            {!! Form::model($item, array('method' => 'put', 'route' => ['admin.itemmodule.update', $item->id], 'data-abide' => '')) !!}
                            <input type="hidden" name="item_id" value="{{ $item->id }}" />
                            <input type="hidden" name="module_id" value="{{ $module->id }}" />
                            <!-- switch the buttons based on state of item -->
                        </td>

                        <td>
                            @if($item->default == '1')
                                <span class="secondary label">Default Item</span>

                            @endif

                        </td>

                        <td>
                            <!--If user is module leader...-->
                            @if(Auth::user()->admin =='2')
                            {{--If items are currently incompleted, show them,--}}
                            @if ($item->pivot->complete != '1')
                                    <!-- completed submit button -->

                            <button type="submit" name="{{$item->id}}markcomplete" class="button tiny">Mark as Complete</button>

                            <input type="hidden" name="complete" value="1" id="{{$item->id}}hiddencomplete" />
                            {{--Return all items that are marked as complete and give the user the option to render them incomplete again--}}
                            @else
                                    <!-- uncompleted submit button -->
                            <button type="submit" name="{{$item->id}}markuncomplete" class="button tiny warning" value="Mark as Incomplete">Mark as Incomplete</button>
                            <input type="hidden" name="complete" value="0" id="{{$item->id}}hiddenuncomplete"/>
                            @endif
                            @endif
                            {!! csrf_field() !!}
                            {!! Form::close() !!}
                        </td>


                        @if(Auth::user()->admin =='2')
                            <td>
                                <!--If module leader, then show delete item button-->
                                {!! Form::open(['url' => '/admin/items/' . $item->id, 'onSubmit' => 'return confirm("Are you sure you want to delete this?")']) !!}
                                {!! Form::hidden('_method', 'DELETE') !!}
                                {!! Form::submit('Delete this Item', array('class' => 'button tiny alert', 'name' =>  'delete' . $item->id)) !!}
                                {!! Form::close() !!}
                            </td>
                        @endif
                    </tr>
                @endforeach
                </tbody>
                @endif
            </table>

            @if(Auth::user()->admin == '1')
                <a href="{{ route('admin.modules.edit', $module->id) }}" class="button small warning right">Edit Module</a>
            @endif
    </div>
@stop